namespace DocumentDataAPI.Models.Attributes;

/// <summary>
/// An attribute that excludes a property from being used when generating SQL INSERT statements.
/// For example for ID columns that are autogenerated by the database, and thus cannot be inserted by the user.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ExcludeFromGeneratedInsertStatementAttribute : Attribute
{
}
