name: Build

on:
  pull_request:
    branches: 
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 6.0
    - name: Install dependencies
      run: dotnet restore
      working-directory: DocumentDataAPI/
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: DocumentDataAPI/
